### ISSUE TITLE
TypeError: Cannot read property 'displayName' of null

### ISSUE THREAD

**Issue by LakeYS** [LakeYS/Discord-Trivia-Bot#122]
```
    var name = msg.channel.type === "text"?msg.member.displayName:msg.author.username;
                                                      ^

TypeError: Cannot read property 'displayName' of null
    at Object.exports.parse (/home/server/TriviaBot/triviabot.js:817:55)
    at Client.global.client.on (/home/server/TriviaBot/shard.js:197:19)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at MessageCreateHandler.handle (/home/server/TriviaBot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/server/TriviaBot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/home/server/TriviaBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/server/TriviaBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/server/TriviaBot/node_modules/ws/lib/event-target.js:120:16)
```

**Comment by LakeYS** [comment]
Unable to replicate after 2 weeks, closing.
