### ISSUE TITLE
TypeError: Cannot read property 'members' of undefined

### ISSUE THREAD

**Issue by LakeYS** [LakeYS/Discord-Trivia-Bot#142]
```
/home/server/TriviaBot/node_modules/discord.js/src/structures/Guild.js:235
          this.channels.get(voiceState.channel_id).members.set(member.user.id, member);
                                                  ^

TypeError: Cannot read property 'members' of undefined
    at Guild.setup (/home/server/TriviaBot/node_modules/discord.js/src/structures/Guild.js:235:51)
    at GuildCreateHandler.handle (/home/server/TriviaBot/node_modules/discord.js/src/client/websocket/packets/handlers/GuildCreate.js:12:15)
    at WebSocketPacketManager.handle (/home/server/TriviaBot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/home/server/TriviaBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/server/TriviaBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/server/TriviaBot/node_modules/ws/lib/event-target.js:120:16)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver._receiver.onmessage (/home/server/TriviaBot/node_modules/ws/lib/websocket.js:137:47)
    at Receiver.dataMessage (/home/server/TriviaBot/node_modules/ws/lib/receiver.js:397:14)
```

**Comment by LakeYS** [comment]
Stale
