### ISSUE TITLE
Some shards do not come back online after an ECONNRESET error

### ISSUE THREAD

**Issue by LakeYS** [LakeYS/Discord-Trivia-Bot#160]
SEE ALSO: #175 

Some shards do not come back online after an ECONNRESET error, seemingly at random
m. Checking the status returns 0, but checking guilds or users returns empty. Properties like "readyAt" and "uptime" return null.

```
manager.broadcastEval("console.log(client.shard.id, client.status);");
```

EDIT: This error may also be related
```
(node:12329) UnhandledPromiseRejectionWarning: Error: Shard 1's process exited b
efore its Client became ready.
    at Shard.once (/home/server/TriviaBot/node_modules/discord.js/src/sharding/S
hard.js:88:39)
    at Object.onceWrapper (events.js:285:13)
    at Shard.emit (events.js:197:13)
    at Shard._handleExit (/home/server/TriviaBot/node_modules/discord.js/src/sha
rding/Shard.js:272:10)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
(node:12329) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 204)
```

Hack fix that resolves the issue when the corresponding shard ID is used:
`manager.broadcastEval("if(client.shard.id === 0) process.exit();");`

EDIT 2019/6/24: This has now been observed taking down every shard with an ETIMEDOUT error. This happened following [this incident](https://status.discordapp.com/incidents/2gztsrksff0v). The bot had to be manually reset to resolve the problem.

**Comment by LakeYS** [comment]
Will not be fixing in v1.6.2 because I'm still having trouble reproducing it in any form. There have not been any occurrences of this in roughly a month.

**Comment by LakeYS** [comment]
This has resurfaced today with several shards being down as a result after Discord's recent outage. The following error occurred on shards that did not come back afterwards:
```
(node:27846) UnhandledPromiseRejectionWarning: Error: Shard 9's Client took too long to become ready.
    at Timeout.setTimeout [as _onTimeout] (/home/server/TriviaBot/node_modules/discord.js/src/shardin
g/Shard.js:89:31)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
(node:27846) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated eit
her by throwing inside of an async function without a catch block, or by rejecting a promise which wa
s not handled with .catch(). (rejection id: 132)
```

**Comment by LakeYS** [comment]
Observed again today following this incident:
https://status.discordapp.com/incidents/gtvzqy8b2plz

**Comment by LakeYS** [comment]
No-longer finding any cases of this. Will continue to monitor for further problems.
