### ISSUE TITLE
TypeError: Cannot read property 'refresh' of undefined

### ISSUE THREAD

**Issue by LakeYS** [LakeYS/Discord-Trivia-Bot#164]
```
Error parsing advanced game data. Dumping...
TypeError: Cannot read property 'refresh' of undefined
    at doAdvAction (/home/server/TriviaBot/lib/cmd_play_advanced.js:355:25)
    at parseAdv (/home/server/TriviaBot/lib/cmd_play_advanced.js:407:5)
    at Object.Trivia.parse (/home/server/TriviaBot/triviabot.js:1443:3)
    at Client.global.client.on (/home/server/TriviaBot/shard.js:156:19)
    at Client.emit (events.js:197:13)
    at MessageCreateHandler.handle (/home/server/TriviaBot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/server/TriviaBot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (/home/server/TriviaBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/server/TriviaBot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/server/TriviaBot/node_modules/ws/lib/event-target.js:120:16)
```

Also recorded happening shortly before this:
```
TypeError: Cannot read property 'replace' of undefined
    at Object.advActions.channel (/home/server/TriviaBot/lib/cmd_play_advanced.js:212:25)
    at parseAdvArgs (/home/server/TriviaBot/lib/cmd_play_advanced.js:288:44)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:5897) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at parseAdvArgs (/home/server/TriviaBot/lib/cmd_play_advanced.js:306:89)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:5897) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)
```

This configuration was reportedly in use when this occurred: `trivia play advanced 2 animals 1 2 #trivia`

**Comment by LakeYS** [comment]
Unable to reproduce
