### ISSUE TITLE
Failover import error

### ISSUE THREAD

**Issue by LakeYS** [LakeYS/Discord-Trivia-Bot#173]
```
Successfully launched shard 0 of 29
Contents of file "game.0.json.bak" are empty, defaulting to shard 0
Contents of file "game.1.json.bak" are empty, defaulting to shard 1
Contents of file "game.2.json.bak" are empty, defaulting to shard 2
Contents of file "game.3.json.bak" are empty, defaulting to shard 3
Contents of file "game.4.json.bak" are empty, defaulting to shard 4
Contents of file "game.5.json.bak" are empty, defaulting to shard 5
Contents of file "game.6.json.bak" belong to shard 1
Contents of file "game.7.json.bak" belong to shard 16
Contents of file "game.8.json.bak" are empty, defaulting to shard 8
Contents of file "game.9.json.bak" are empty, defaulting to shard 9
Contents of file "game.10.json.bak" are empty, defaulting to shard 10
Contents of file "game.11.json.bak" are empty, defaulting to shard 11
Contents of file "game.12.json.bak" are empty, defaulting to shard 12
Contents of file "game.13.json.bak" belong to shard 0
Contents of file "game.14.json.bak" are empty, defaulting to shard 14
Contents of file "game.15.json.bak" are empty, defaulting to shard 15
Contents of file "game.16.json.bak" belong to shard 16
Contents of file "game.17.json.bak" are empty, defaulting to shard 17
Contents of file "game.18.json.bak" are empty, defaulting to shard 18
Contents of file "game.19.json.bak" are empty, defaulting to shard 19
Contents of file "game.20.json.bak" are empty, defaulting to shard 20
Contents of file "game.21.json.bak" are empty, defaulting to shard 21
Contents of file "game.22.json.bak" are empty, defaulting to shard 22
Contents of file "game.23.json.bak" are empty, defaulting to shard 23
Contents of file "game.24.json.bak" belong to shard 10
Contents of file "game.25.json.bak" are empty, defaulting to shard 25
Contents of file "game.26.json.bak" are empty, defaulting to shard 26
Contents of file "game.27.json.bak" belong to shard 7
Contents of file "game.28.json.bak" are empty, defaulting to shard 28
Exported 2 game(s) to ./game.0.json.bak
Exported 1 game(s) to ./game.1.json.bak
Exported 0 game(s) to ./game.2.json.bak
Exported 0 game(s) to ./game.3.json.bak
Exported 0 game(s) to ./game.4.json.bak
Exported 0 game(s) to ./game.5.json.bak
Exported 0 game(s) to ./game.6.json.bak
Exported 1 game(s) to ./game.7.json.bak
Exported 0 game(s) to ./game.8.json.bak
Exported 0 game(s) to ./game.9.json.bak
Exported 1 game(s) to ./game.10.json.bak
Exported 0 game(s) to ./game.11.json.bak
Exported 0 game(s) to ./game.12.json.bak
Exported 0 game(s) to ./game.13.json.bak
Exported 0 game(s) to ./game.14.json.bak
Exported 0 game(s) to ./game.15.json.bak
Exported 2 game(s) to ./game.16.json.bak
Exported 0 game(s) to ./game.17.json.bak
Exported 0 game(s) to ./game.18.json.bak
Exported 0 game(s) to ./game.19.json.bak
Exported 0 game(s) to ./game.20.json.bak
Exported 0 game(s) to ./game.21.json.bak
Exported 0 game(s) to ./game.22.json.bak
Exported 0 game(s) to ./game.23.json.bak
Exported 0 game(s) to ./game.24.json.bak
Exported 0 game(s) to ./game.25.json.bak
Exported 0 game(s) to ./game.26.json.bak
Exported 0 game(s) to ./game.27.json.bak
Exported 0 game(s) to ./game.28.json.bak
Importing games to shard 0 from file...
Shard 0 connected to 997 servers.
Successfully launched shard 1 of 29
Exit with non-zero code, exporting game data...
Game exported to ./game.0.json.bak
/home/server/TriviaBot/triviabot.js:519
        var roundEndCount = getConfigVal("rounds-end-after", channel.id)-game[id
].emptyRoundCount;
                                                                     ^

TypeError: Cannot read property 'id' of undefined
    at Object.Trivia.doAnswerReveal (/home/server/TriviaBot/triviabot.js:519:70)
    at Timeout.game.(anonymous function).timeout.setTimeout [as _onTimeout] (/home/server/TriviaBot/triviabot.js:1521:14)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
```

**Comment by LakeYS** [comment]
Stale
