### ISSUE TITLE
TypeError: Cannot read property 'channels' of null

### ISSUE THREAD

**Issue by LakeYS** [LakeYS/Discord-Trivia-Bot#176]
```
/home/server/TriviaBot/lib/cmd_stop.js:14
        stopChannel = msg.guild.channels.find((obj) => (obj.id === idInput));
                                ^

TypeError: Cannot read property 'channels' of null
    at Object.triviaStop (/home/server/TriviaBot/lib/cmd_stop.js:14:33)
    at parseCommand (/home/server/TriviaBot/triviabot.js:1186:14)
    at Object.Trivia.parse (/home/server/TriviaBot/triviabot.js:1463:5)
    at Client.global.client.on (/home/server/TriviaBot/shard.js:160:19)
    at Client.emit (events.js:193:13)
    at MessageCreateHandler.handle (/home/server/TriviaBot/node_modules/discord.
js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/server/TriviaBot/node_modules/discor
d.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/home/server/TriviaBot/node_modules/discord
.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/server/TriviaBot/node_modules/discor
d.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/server/TriviaBot/node_modules/ws/lib/event-tar
get.js:120:16)
```

**Comment by LakeYS** [comment]
No further reports, likely stale
