### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by LakeYS** [LakeYS/Discord-Trivia-Bot#183]
```
Shard 12 connected to 1396 servers.
DEBUG [13]: [ws] [connection] Heartbeat acknowledged, latency of 2354ms
Exit with non-zero code, exporting game data...
Game exported to ./game.12.json.bak
/home/server/TriviaBot/triviabot.js:522
        var roundEndCount = getConfigVal("rounds-end-after", channel.id)-game[id].emptyRoundC
ount;
                                                                     ^

TypeError: Cannot read property 'id' of undefined
    at Object.Trivia.doAnswerReveal (/home/server/TriviaBot/triviabot.js:522:70)
    at Timeout.game.(anonymous function).timeout.setTimeout [as _onTimeout] (/home/server/Tri
viaBot/triviabot.js:1524:14)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
Shard 12 closed unexpectedly! PID: 30927; Exit code: 1.
Successfully launched shard 12 of 24
```

**Comment by LakeYS** [comment]
Stale
