### ISSUE TITLE
advanced game is not started when "use-fixed-rounds": true

### ISSUE THREAD

**Issue by Peterr-K** [LakeYS/Discord-Trivia-Bot#208]
#Hi

on this github version, when I set
`"use-fixed-rounds": true,`
the advanced game is not started after the configuration, last message is "starting the game in channel xxx"

@Deldaflyer

**Comment by LakeYS** [comment]
Uncaught error displayed on attempt of round start
```
(node:16092) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'c
ustomRoundCount' of undefined
    at Object.Trivia.doGame (C:\Content\Dev\_Discord\Discord-Trivia-Bot\triviabo
t.js:952:36)
    at startAdvGame (C:\Content\Dev\_Discord\Discord-Trivia-Bot\lib\cmd_play_adv
anced.js:79:29)
    at parseAdvArgs (C:\Content\Dev\_Discord\Discord-Trivia-Bot\lib\cmd_play_adv
anced.js:314:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at emitUnhandledRejectionWarning (internal/process/promises.js:149:15)
    at processPromiseRejections (internal/process/promises.js:211:11)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
(node:16092) TypeError: Cannot set property 'customRoundCount' of undefined
    at Object.Trivia.doGame (C:\Content\Dev\_Discord\Discord-Trivia-Bot\triviabo
t.js:952:36)
    at startAdvGame (C:\Content\Dev\_Discord\Discord-Trivia-Bot\lib\cmd_play_adv
anced.js:79:29)
    at parseAdvArgs (C:\Content\Dev\_Discord\Discord-Trivia-Bot\lib\cmd_play_adv
anced.js:314:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:16092) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:161:11)
    at processPromiseRejections (internal/process/promises.js:213:13)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```
