### ISSUE TITLE
Interaction errors in "This round has already ended" reply action

### ISSUE THREAD

**Issue by LakeYS** [LakeYS/Discord-Trivia-Bot#244]
Appears to coincide with degraded performance on either the bot's or Discord's end. The cause is unknown, but we should be able to remedy this by adding catches to the following action, and subsequent calls:
https://github.com/LakeYS/Discord-Trivia-Bot/blob/master/lib/platform/discord_shard.js#L120

A catch with an error should also attempt to dump any available info about the interaction object prior to calling upon it.

```
/home/trivia/trivia/node_modules/discord.js/src/rest/RequestHandler.js:349
      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Unknown interaction
    at RequestHandler.execute (/home/trivia/trivia/node_modules/discord.js/src/rest/RequestHandler.js:349:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/home/trivia/trivia/node_modules/discord.js/src/rest/RequestHandler.js:50:14)
    at async ButtonInteraction.reply (/home/trivia/trivia/node_modules/discord.js/src/structures/interfaces/Int
eractionResponses.js:98:5) {
  method: 'post',
  path: '/interactions/919018517234352188/aW50ZXJhY3Rpb246OTE5MDE4NTE3MjM0MzUyMTg4OmhSRlVhQ2dkbUVNOTF0djVNUU9Je
UdQQXV5YjIxck80Z0F2ZUNwRFF6dzRzT2xCQjB3dWxmMG9DMUJwN09aWEdNSm83dXdvSEk3dm9hRzVEVm1tUkZ6ckFIelUzcmYyZU5mUVZvWXFt
ekZ4MVR0QlBnRUJuVlZZMmxrN3UxT3hL/callback',
  code: 10062,
  httpStatus: 404,
  requestData: {
    json: {
      type: 4,
      data: {
        content: 'This round has already ended.',
        tts: false,
        nonce: undefined,
        embeds: undefined,
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: 64,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined
      }
    },
    files: []
  }
}
```

**Comment by LakeYS** [comment]
Addressed in ef6e4b39 (2.0) and 70e85476 (1.x)
