### ISSUE TITLE
"DiscordAPIError: Unknown interaction" during disruptions while submitting answer

### ISSUE THREAD

**Issue by LakeYS** [LakeYS/Discord-Trivia-Bot#248]
It is suspected that this error is occurring on the main bot when there is a degraded connection.

Reproduction using Visual Studio Code:
1. Set up Visual Studio code to launch the bot. Set a breakpoint within game.js under the submitAnswer function.
2. Start the bot and run a standard game using `trivia play`
3. Select an answer. Wait for the "This interaction failed" message
4. Click resume and note the error.

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

DiscordAPIError: Unknown interaction
    at RequestHandler.execute (C:\Content\Dev\_Discord\Discord-Trivia-Bot\node_modules\discord.js\src\rest\RequestHandler.js:349:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (C:\Content\Dev\_Discord\Discord-Trivia-Bot\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async ButtonInteraction.update (C:\Content\Dev\_Discord\Discord-Trivia-Bot\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:210:5) {
  method: 'post',
  path: '/interactions/920425605818908722/aW50ZXJhY3Rpb246OTIwNDI1NjA1ODE4OTA4NzIyOnp3Z0tCajhNeWhRRkxDdDRpT2ZiSWt1bmNtQ2pYaU14UzhZQlBSZ1RPOTJHZ2RsOHRTSkNReVo0U2FOZGxOdE9sNGlEYVozZFFyUXZXZk9PcUx0SkdBbWhrTk9rdlRvR3ZVUXI2MlRxRUlLTlB0OGZaNmtkSm5JRGtKMlRRMDhU/callback',
  code: 10062,
  httpStatus: 404,
  requestData: {
    json: {
      type: 7,
      data: {
        content: 'Answered!',
        tts: false,
        nonce: undefined,
        embeds: undefined,
        components: undefined,
        username: undefined,
        avatar_url: undefined,
        allowed_mentions: undefined,
        flags: undefined,
        message_reference: undefined,
        attachments: undefined,
        sticker_ids: undefined
      }
    },
    files: []
  }
}
```

**Comment by LakeYS** [comment]
Addressed in ef6e4b3 (2.0) and 70e8547 (1.x), with further handling in 6372d30 and b47f0c6.
